app/auth/signup/_layout.tsx, app/auth/signup/account.tsx, app/auth/signup/done.tsx, app/auth/signup/profile.tsx, app/auth/signup/university-details.tsx
Keyboard 리스터 등록해서 키보드 창이 나오면 하단 버튼들이 보이지 않도록 추가
=> fix: 모바일에서 폼 입력 시 하단 버튼들이 위로 올라오는거 수정

src/features/community/apis/articles.tsx, src/features/community/apis/comments.tsx, src/features/community/hooks/use-articles.tsx, src/features/community/hooks/use-infinite-articles.tsx, src/features/community/ui/article/index.tsx, src/features/community/ui/article/interaction-nav.tsx, src/features/community/ui/infinite-article-list.tsx, src/shared/hooks/use-infinite-data.ts, src/shared/infinite-scroll/types.ts, src/shared/libs/image.ts
이 PR은 커뮤니티 게시글에 대한 좋아요 기능을 구현하고, 게시글 UI를 개선하는 작업을 포함합니다.
- 게시글 좋아요 API 연동 (`doLike` 메서드 추가)
- 좋아요 상태에 따른 UI 변경 (하트 아이콘 활성화/비활성화)
- 좋아요 카운트 실시간 업데이트 기능 구현
- 낙관적 UI 업데이트 적용 (API 응답 전 UI 먼저 업데이트)
- 좋아요 활성화 상태를 위한 `HEART_ON` 이미지 리소스 추가
- `ImageResources` 열거형에 새 리소스 추가
- 좋아요 상태에 따른 조건부 렌더링 구현
- 게시글 작성 시간 표시 위치 및 스타일 개선
- 상호작용 컴포넌트(좋아요, 댓글, 조회수) 기능 강화
- 댓글 표시/숨김 기능 개선
- `useInfiniteData` 훅에 `setData` 메서드 노출하여 외부에서 데이터 업데이트 가능하도록 개선
- 특정 게시글만 업데이트하는 `toggleArticleLike` 유틸 함수 구현
- 에러 처리를 위한 `tryCatch` 유틸리티 활용
- `src/features/community/apis/articles.tsx`: 좋아요 API 메서드 추가
- `src/features/community/ui/article/index.tsx`: 좋아요 기능 및 UI 개선
- `src/features/community/ui/article/interaction-nav.tsx`: 좋아요 상태에 따른 아이콘 변경
- `src/features/community/ui/infinite-article-list.tsx`: 좋아요 기능 연동
- …
=> feat: 커뮤니티 메인 - 좋아요 기능 

app/community/index.tsx, app/community/write.tsx, src/features/auth/hooks/use-auth.tsx, src/features/community/apis/articles.tsx, src/features/community/hooks/article-writer/index.tsx, src/features/community/hooks/index.tsx, src/features/community/index.tsx, src/features/community/services/article-writer.tsx, src/features/community/services/index.ts, src/features/community/ui/article-write-screen/index.tsx, src/features/community/ui/article-write-screen/ui/form.tsx, src/features/community/ui/article-write-screen/ui/header.tsx, src/features/community/ui/article-write-screen/ui/index.tsx, src/features/community/ui/article/index.tsx, src/features/community/ui/create-article-fab.tsx, src/features/community/ui/index.tsx, src/features/community/ui/infinite-article-list.tsx, src/types/user.ts
이 PR은 커뮤니티 게시글 작성 기능을 구현하고, 게시글 작성 후 목록 페이지로 돌아갔을 때 데이터를 자동으로 새로고침하는 기능을 추가합니다.
- 게시글 작성 폼 UI 구현 (제목, 내용, 익명 여부 설정)
- 게시글 작성 API 연동 (`postArticles` 메서드 활용)
- 카테고리별 게시글 작성 기능 지원 (URL 쿼리 파라미터 활용)
- 폼 유효성 검사 추가 (제목, 내용 최소 길이 검증)
- 게시글 작성 화면을 여러 컴포넌트로 분리하여 관심사 분리
- `ArtcileWriter.Header`: 헤더 컴포넌트 (뒤로가기, 완료 버튼)
- `ArtcileWriter.Form`: 게시글 작성 폼 컴포넌트
- `ArticleWriteFormProvider`: 폼 상태 관리를 위한 컨텍스트 제공자
- URL 쿼리 파라미터를 활용한 데이터 리로딩 메커니즘 구현
- `forwardRef`와 `useImperativeHandle`을 활용한 컴포넌트 간 메서드 공유
- 게시글 작성 완료 후 목록 페이지로 리다이렉션 시 `refresh=true` 파라미터 추가
- 목록 페이지에서 `refresh` 파라미터 감지 및 데이터 새로고침 처리
- React Hook Form을 활용한 효율적인 폼 상태 관리
- 커스텀 훅 `useArticleWriteForm`을 통한 폼 로직 분리
- 익명 게시글 작성 기능 구현 (체크박스 토글)
- `src/features/community/hooks/article-writer/index.tsx`: 게시글 작성 폼 관련 훅
- …
=> feat: 게시글 작성 및 신규 게시글 작성 리로드

app/community/[id].tsx, app/community/_layout.tsx, app/community/index.tsx, app/community/update/[id].tsx, app/community/write.tsx, src/features/community/apis/articles.tsx, src/features/community/hooks/article-writer/index.tsx, src/features/community/queries/articles.tsx, src/features/community/queries/index.tsx, src/features/community/queries/keys.ts, src/features/community/ui/article-write-screen/index.tsx, src/features/community/ui/article-write-screen/ui/form.tsx, src/features/community/ui/article-write-screen/ui/header.tsx, src/features/community/ui/article-write-screen/ui/index.tsx, src/features/community/ui/article-write-screen/ui/nav.tsx, src/features/community/ui/article/index.tsx, src/features/community/ui/category-list/index.tsx, src/features/community/ui/infinite-article-list.tsx, src/shared/libs/day.ts, src/shared/libs/image.ts, src/shared/ui/button/index.tsx, src/shared/ui/check/index.tsx, src/shared/ui/dropdown/index.tsx, src/shared/ui/index.tsx
이 브랜치에서는 커뮤니티 게시글의 삭제 및 수정 기능을 구현했습니다. 주요 작업 내용은 다음과 같습니다:
1. 게시글 삭제 기능 구현
2. 게시글 수정 기능 구현
3. 드롭다운 메뉴 컴포넌트 개발
4. UI 스타일 개선 및 버그 수정
- 새로운 드롭다운 컴포넌트를 `src/shared/ui/dropdown/index.tsx`에 구현
- 드롭다운 메뉴가 화면 밖으로 나가지 않도록 위치 조정
- 이벤트 전파 문제 해결을 위한 `e.stopPropagation()` 적용
- 웹 환경에서 외부 클릭 시 드롭다운이 닫히도록 구현
- 게시글 삭제 API 연동
- 삭제 확인 모달 구현
- 삭제 후 게시글 목록 자동 갱신
- 게시글 수정 API 연동
- 수정 페이지 구현 (`app/community/update/[id].tsx`)
- 기존 게시글 내용 불러오기 및 수정 폼 구현
- 수정 완료 후 상세 페이지로 이동
- 게시글 작성 폼 컴포넌트 구조 개선
- 익명 체크박스 UI 개선
- 체크박스 컴포넌트에 children 요소 추가 기능
- 커뮤니티 로고 및 헤더 스타일 개선
- 카테고리 목록 스타일 개선
- 버튼 컴포넌트에 'black' 텍스트 색상 옵션 추가
- `src/shared/ui/dropdown/index.tsx`: 새로운 드롭다운 컴포넌트 구현
- `src/features/community/ui/article/index.tsx`: 게시글 항목에 드롭다운 메뉴 통합
- `src/features/community/ui/infinite-article-list.tsx`: 게시글 삭제 기능 구현
- …
=> feature: 게시글 수정/삭제 기능

app/auth/signup/done.tsx, app/community/index.tsx, app/home/index.tsx, app/interest/_layout.tsx, app/interest/dating-style.tsx, app/interest/done.tsx, app/interest/interest.tsx, app/interest/military.tsx, app/interest/smoking.tsx, app/interest/tattoo.tsx, src/features/auth/hooks/use-auth.tsx, src/features/community/queries/use-infinite-articles.tsx, src/features/community/ui/article/index.tsx, src/features/community/ui/infinite-article-list.tsx, src/features/home/apis/index.tsx, src/features/home/hooks/index.tsx, src/features/home/index.tsx, src/features/home/queries/index.tsx, src/features/interest/hooks/use-interest-form.tsx, src/features/interest/queries/index.tsx, src/features/interest/services/index.tsx, src/features/interest/ui/age-selector.tsx, src/shared/constants/colors.ts, src/shared/hooks/use-infinite-data.ts, src/shared/hooks/use-storage.ts, src/shared/infinite-scroll/custom-infinite-scroll-view.tsx, src/shared/libs/image.ts, src/shared/ui/announce-card/index.tsx, src/shared/ui/index.tsx, src/shared/ui/text/index.tsx
이 브랜치는 사용자 이상형 정보 관련 기능 개선 및 버그 수정을 위한 작업을 포함하고 있습니다. 주요 작업 내용은 이상형 정보 안내 모달 기능 추가, 무한 스크롤 훅 개선, 스토리지 관련 버그 수정 등입니다.
- `use-auth.tsx` 파일에서 useEffect 훅을 컴포넌트 최하단으로 이동
- 코드 가독성 및 일관성 향상을 위한 리팩토링
- 이상형 정보가 없는 사용자에게 안내 모달을 표시하는 기능 추가
- 이상형 정보 입력 여부를 확인하는 API 연동
- 사용자가 '나중에 할게요' 선택 시 일정 기간(1일) 동안 모달을 다시 표시하지 않는 기능 구현
- 관련 스토리지 상태 관리 로직 구현
- `use-infinite-data.ts` 파일의 refresh 함수 로직 개선
- 데이터 새로고침 시 로딩 상태 관리 로직 추가
- 에러 처리 및 로딩 상태 정리 로직 추가
- 스토리지 값 로드 및 저장 시 발생하는 직렬화 관련 버그 수정
- useRef를 사용하여 initialValue 참조 안정성 보장
- useEffect 의존성 배열에서 initialValue 제거하여 불필요한 리렌더링 방지
- 상태 업데이트 전 이전 값과 비교하여 불필요한 업데이트 방지
- 디버깅 로그 정리
- 이상형 관련 이미지 리소스 추가
- 데이팅 스타일 이미지 (DATING_STYLE)
- 군대 관련 이미지 (MILITARY)
1. **상태 관리 최적화**
- useStorage 훅의 불필요한 리렌더링 문제 해결
- 참조 안정성 보장을 위한 useRef 활용
- 상태 업데이트 최적화를 위한 비교 로직 추가
2. **사용자 경험 …
=> feat: 이상형 정보 요구 및 입력 기능

src/features/admin/index.tsx, src/features/admin/services/index.tsx, src/features/signup/ui/login-form.tsx
다음 사용자는 서비스 접속이 허용됩니다.
```bash
01965d49-995d-7c5b-a469-39e1f28520a0,유재윤,20211072@edu.hanbat.ac.kr
0196629a-0c5f-75b6-9b6e-8b9328e264a4,전준영,kwysome@gmail.com
019664c5-db77-77ca-a87f-cb68add3c820,최은기,deveungi@gmail.com
01966a4f-6f22-713b-b287-dc62e74bf1a3,이지효,leeji3301@naver.com
01966c70-5447-7409-997d-06b5ecd9b264,양예원,yangdl38@naver.com
```
- `login-form.tsx` 파일에서 하드코딩된 예외 처리 로직을 관리자 서비스로 분리
- 로그인 시 인증 상태에 따른 리다이렉션 로직 활성화
- 비밀번호 정규식 검증 활성화
- 관리자 기능을 위한 새로운 모듈 구조 생성
- 예외 이메일 목록 관리를 위한 서비스 로직 구현
- 프로덕션 환경에서 특정 이메일 사용자에게 다른 경로 제공
1. **코드 구조 개선**
- 하드코딩된 예외 처리 로직을 별도 서비스로 분리하여 모듈화
- 관리자 기능을 위한 명확한 디렉토리 구조 생성
2. **유지보수성 향상**
- 예외 이메일 목록을 중앙 집중식으로 관리하여 변경 용이성 확보
- 환경별 로그인 처리 로직 명확화
3. **보안 강화**
- 비밀번호 정규식 검증 활성화로 보안 수준 향상
- 인증 상태에 따른 적절한 리다이렉션 처리
다음 이메일 주소를 가진 사용자들은 프로덕션 환경에서도 홈 화면으로 접근 가능:
- …
=> feature: 로그인 - 내부사용자 로그인 서비스 접속 허용

app/auth/signup/account.tsx, app/home/index.tsx, src/features/admin/hooks/index.tsx, src/features/admin/hooks/use-comming-soon.tsx, src/features/admin/index.tsx, src/features/idle-match-timer/index.tsx, src/features/idle-match-timer/ui/pre-open.tsx, src/shared/libs/image.ts, src/shared/ui/text/index.tsx
- `ImageResource` 컴포넌트에 반응형 크기 적용
- 모바일 환경에서는 이미지 크기를 절반으로 줄이도록 수정
- `platform` 유틸리티를 사용하여 디바이스별 크기 조정
`useCommingSoon` 훅은 "준비중인 기능입니다"라는 메시지를 보여주는 모달을 쉽게 표시할 수 있게 해주는 유틸리티 훅입니다.
```tsx
import { useCommingSoon } from '@/src/features/admin/hooks';
export default function MyComponent() {
const showCommingSoon = useCommingSoon();
return (
<TouchableOpacity onPress={showCommingSoon}>
<Text>준비중인 기능</Text>
</TouchableOpacity>
);
}
```
```tsx
// app/home/index.tsx
const showCommingSoon = useCommingSoon();
const onRedirectTicketPurChase = () => {
environmentStrategy({
production: () => {
showCommingSoon();
},
development: () => {
router.navigate('/purchase/tickets/rematch');
}
})
};
```
이 훅을 사용하면 일관된 UI/UX로 준비중인 기능을 사용자에게 알릴 수 있습니다.
=> feature: 사전 오픈을 위한 일부 기능 추가

src/shared/ui/business-info/business-info.tsx
- business-info.tsx 파일의 사업장 소재지 주소 변경
=> chore: 사업자 주소 변경

app/_layout.tsx, app/matching-history/_layout.tsx, app/partner/view/[id].tsx, src/features/community/ui/user-profile/index.tsx, src/features/idle-match-timer/hooks/use-rematch.tsx, src/features/idle-match-timer/ui/partner.tsx, src/features/match/ui/partner-image/index.tsx, src/features/matching-history/apis/index.tsx, src/features/matching-history/queries/use-unlock-profile.tsx, src/features/matching-history/ui/matching-history-card.tsx, src/features/profile-edit/ui/header.tsx, src/features/setting/ui/setting-header.tsx
=> Feat: 이전 매칭 프로필 풀기 작업

app.json, app/_layout.tsx, app/home/index.tsx, app/purchase/_layout.tsx, app/purchase/gem-store.tsx, babel.config.js, package-lock.json, package.json, src/features/payment/api/index.ts, src/features/payment/hooks/index.tsx, src/features/payment/hooks/use-current-gem.tsx, src/features/payment/hooks/use-gem-products.tsx, src/features/payment/hooks/use-portone.tsx, src/features/payment/ui/gem-store/banner.tsx, src/features/payment/ui/gem-store/gem-product-list.tsx, src/features/payment/ui/gem-store/header.tsx, src/features/payment/ui/gem-store/index.tsx, src/features/payment/ui/index.tsx, src/shared/libs/image.ts, src/shared/libs/notifications.ts, src/shared/ui/header/ui/container.tsx, src/shared/ui/header/ui/left-button.tsx, src/shared/ui/header/ui/logo.tsx, src/widgets/gem-store/index.tsx, src/widgets/gem-store/utils/index.ts, src/widgets/header/index.tsx, src/widgets/index.tsx
- 재화 ui 를 작성하였으며 결제 기능까지 1차적으로 연동했습니다.
- 코드는 기존 페이먼츠 기반으로 작성하였으며 복잡도 문제는 유지되었습니다. (리팩터링 비용 상당히 높음)
- 결제를 수행하면 실제 PG 에서 차감이되나 재화가 충전되지 않은 현상은 개발환경이라 자연스러운 현상입니다. (테스트 결제로 특정 시간 이후 다시 환불됨)
공용으로 사용하는 헤더가 2개가있는데 (하나로 통합필요..)
그중 제일 정상적으로 작동하는 헤더에 대해 스타일 리뉴얼을 수행했습니다.
=> feat: 재화 스토어 UI 추가 / 결제 기능 추가

app/auth/signup/area.tsx, app/test/index.tsx, src/shared/providers/modal-provider.tsx
useModal의 showModal 를 사용할 때  boolean 타입의 showLogo 값을 설정하는 것으로 로고를 모달에 포함시킬 수 있음
`
showModal({showLogo: true, ...})
`
=> Feat: 모달에 로고를 추가할 수 있도록 변경

app.json, app/purchase/gem-store.tsx, src/features/event/hooks/use-event-control.tsx, src/features/event/types.ts, src/features/home/ui/first-purchase-event-banner.tsx, src/features/idle-match-timer/ui/nav.tsx, src/features/payment/hooks/use-portone-store.ts, src/features/payment/hooks/use-portone.tsx, src/features/payment/hooks/useFirstSaleEvents.tsx, src/features/payment/types/index.ts, src/features/payment/ui/first-sale-card/index.tsx, src/features/payment/ui/index.tsx, src/features/payment/ui/port-one-payment.tsx, src/shared/hooks/index.tsx, src/shared/hooks/use-scroll-indicator.tsx, src/shared/hooks/use-timer.tsx, src/shared/libs/image.ts, src/shared/libs/index.ts, src/shared/libs/time.ts, src/shared/ui/card/glowing-card.tsx, src/shared/ui/card/index.tsx, src/shared/ui/index.tsx, src/shared/ui/scroll-down-indicator/index.tsx, src/widgets/gem-store/index.tsx
• 신규 회원 대상 최초 구매 특가 이벤트 카드 구현
• 말풍선 UI에 바운스 애니메이션 및 왼쪽 방향 꼬리 추가  
• 스크롤 다운 인디케이터로 하단 구슬 메뉴 접근성 개선
• **FirstSaleCard 컴포넌트**: 타이머와 함께 특가 상품 표시
• **스크롤 인디케이터**: 스크롤 시작 시 자동 숨김 처리
• **말풍선 애니메이션**: reanimated로 자연스러운 바운스 효과
• **이벤트 관리**: 여러 첫 구매 이벤트 타입 지원
=> feat: 최초 구매 특가 이벤트 및 스크롤 인디케이터 구현

app/home/index.tsx, src/features/matching-history/ui/history-collapse.tsx
=> Feat/이전 매칭 진입점 추가

app/test/index.tsx, package-lock.json, package.json, src/features/signup/ui/apple-login-button.tsx, src/features/signup/ui/login-form.tsx
/test 경로에서 웹 애플 로그인 테스트 예정(추후 삭제 예정)
=> Feat/ /test 경로에서 테스트해볼 생각

app/auth/_layout.tsx, app/auth/login/apple-info.tsx, src/features/signup/queries/use-apple-login.tsx
- 애플 로그인 후 필요한 사용자 정보(성별, 생년월일, 전화번호)를 수집합니다.
- 수집한 정보를 로그인 폼으로 넘기도록 합니다.
=> feat: 애플 로그인 후 사용자 정보 수집 UI 퍼블리싱

src/features/community/ui/article-detail/article-detail.tsx
- 커뮤니티 게시글에서 이미지 뷰어를 활용할 수 있습니다.
- 게시글 페이지에서 이미지를 누르면 워터마크가 포함된 이미지 뷰어를 통해 이미지를 크게 볼 수 있습니다.
=> feat: 커뮤니티 게시글 워터마크 이미지 뷰어 적용

src/shared/hooks/use-infinite-scroll.ts, src/shared/infinite-scroll/custom-infinite-scroll-view.tsx, src/shared/infinite-scroll/infinite-scroll-view.tsx
- 웹 환경에서 커뮤니티 게시판 스크롤이 하단에 도달할 때 다음 페이지를 불러오지 못하는 현상이 있었습니다.
- 옵저버를 강화하고 하단 탭 근접에서 다시 게시글을 호출하도록 수정합니다.
=> fix/커뮤니티 스크롤 하단 도달시 다음 페이지를 호출하지 못하는 현상 수정

src/shared/infinite-scroll/custom-infinite-scroll-view.tsx
- useCallback 훅의 부적절한 위치로 인해 게시글 렌더링 실패 현상이 간헐적으로 발생합니다.
- 모든 훅을 같은 순서로 호출하도록 조정합니다.
=> fix/커뮤니티 최대 스크롤시 훅 호출 순서 통일

app/community/update/[id].tsx, app/community/write.tsx, src/features/community/ui/article-write-screen/ui/form.tsx, src/features/community/ui/create-article-fab.tsx
- 커뮤니티에서 글 작성 도중 카테고리 변경이 가능합니다.
- 커뮤니티 글쓰기 기능에 대한 플로팅 액션 버튼 노출 여부를 판단합니다.
- 공지탭: admin에게만 공개 됩니다.
- 인기탭: 인기글을 직접 작성할 수 없으므로 해당 탭에서 글쓰기 버튼이 노출되지 않습니다.
- 글 수정 모드일 경우 카테고리를 변경할 수는 없습니다. 이때 카테고리 선택 버튼이 비활성화 됩니다.
=> feat: 커뮤니티 글쓰기에서 카테고리 변경 및 글쓰기 버튼 노출 분기

src/features/chat/queries/use-chat-lock-query.tsx, src/features/chat/queries/use-chat-snooze-query.tsx, src/features/chat/queries/use-create-chat-room.tsx, src/features/chat/queries/use-leave-chat-room.tsx, src/features/chat/services/chat-snooze-error-handler.tsx, src/features/logger/hooks/use-logger-tabs.tsx, src/features/logger/service/patch.ts
=> Dev -> Deploy (hotfix)
